# Generated by Django 4.0.4 on 2022-07-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='url',
            field=models.SlugField(default='films', max_length=160, unique=True),
        ),
    ]
