# Generated by Django 4.0.4 on 2022-07-01 21:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rewiews_delete_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='born',
            field=models.DateField(default=datetime.date.today, verbose_name='Born'),
        ),
        migrations.AddField(
            model_name='actor',
            name='end_acting',
            field=models.CharField(default='present', max_length=100, verbose_name='End'),
        ),
        migrations.AddField(
            model_name='actor',
            name='genre',
            field=models.ManyToManyField(to='movies.genre', verbose_name='genre'),
        ),
        migrations.AddField(
            model_name='actor',
            name='nationality',
            field=models.CharField(default='USA', max_length=100, verbose_name='Nationality'),
        ),
        migrations.AddField(
            model_name='actor',
            name='start_acting',
            field=models.PositiveSmallIntegerField(default=1980, verbose_name='Start'),
        ),
    ]
