# Generated by Django 4.0.4 on 2022-07-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_actorgenre_alter_ratingstar_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='genre',
            field=models.ManyToManyField(to='movies.actorgenre', verbose_name='genre'),
        ),
    ]
