# Generated by Django 4.0.4 on 2022-07-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_actor_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='genre',
        ),
        migrations.AddField(
            model_name='actor',
            name='genre',
            field=models.CharField(default='Adventure, Drama', max_length=100, verbose_name='Name'),
        ),
        migrations.DeleteModel(
            name='ActorGenre',
        ),
    ]
